version: '3.8'

services:

  server :
    build:  ./
    command: ./server
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - mongodb
      - front


  front:
    build: 
      context: ../eCRF-front/frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    volumes:
      - .:/front

  postgres:
    restart: always 
    image: postgres:latest
    environment:
        POSTGRES_USER: ${PG_DB_USER}
        POSTGRES_PASSWORD: ${PG_DB_PASS}
        POSTGRES_DB: ${PG_DB_NAME}

    volumes:
        - dbdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_DB_USER} -d ${PG_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5



  mongodb:
    image : mongo
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /home/barry/mongodb/database:/data/db
    ports:
    - 27016:27017
    restart: unless-stopped

volumes:
  dbdata: # persist database
