definitions:
  requests.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  requests.Registration:
    properties:
      center_id:
        type: integer
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: integer
    type: object
  responses.Error:
    properties:
      message:
        type: string
    type: object
  responses.Login:
    properties:
      JWT:
        type: string
    type: object
  responses.Registration:
    properties:
      center_id:
        type: integer
      email:
        type: string
      name:
        type: string
      role:
        type: integer
      user_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: authentification user in the system
      parameters:
      - description: login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Login'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: User Login
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: registration of user
      parameters:
      - description: registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.Registration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Registration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: User Registration
      tags:
      - User
swagger: "2.0"
