definitions:
  requests.AddCenter:
    properties:
      name:
        type: string
    type: object
  requests.AddProtocol:
    properties:
      centerID:
        type: integer
      name:
        type: string
      status:
        type: integer
    type: object
  requests.Delete:
    properties:
      id:
        type: integer
    type: object
  requests.DeleteCenter:
    properties:
      center_id:
        type: integer
    type: object
  requests.DeleteProtocol:
    properties:
      id:
        type: integer
    type: object
  requests.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  requests.Registration:
    properties:
      center_id:
        type: integer
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: integer
    type: object
  requests.SaveProtocol:
    properties:
      centerId:
        type: integer
      id:
        type: integer
      name:
        type: string
      status:
        type: integer
    type: object
  requests.Update:
    properties:
      center_id:
        type: integer
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        type: integer
    type: object
  requests.UpdateCenter:
    properties:
      center_id:
        type: integer
      name:
        type: string
    type: object
  responses.AddProtocol:
    properties:
      message:
        type: string
    type: object
  responses.Center:
    properties:
      center_id:
        type: integer
      center_name:
        type: string
    type: object
  responses.DeleteProtocol:
    properties:
      message:
        type: string
    type: object
  responses.Error:
    properties:
      message:
        type: string
    type: object
  responses.GetProtocols:
    properties:
      center_id:
        type: integer
      name:
        type: string
      protocol_id:
        type: integer
      status:
        type: integer
    type: object
  responses.Login:
    properties:
      JWT:
        type: string
    type: object
  responses.Registration:
    properties:
      center_id:
        type: integer
      email:
        type: string
      name:
        type: string
      role:
        type: integer
      user_id:
        type: integer
    type: object
  responses.SaveProtocol:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /center/add:
    post:
      consumes:
      - application/json
      description: add new center
      parameters:
      - description: addcenter
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.AddCenter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DeleteProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Add new  center
      tags:
      - Center
  /center/all:
    get:
      consumes:
      - application/json
      description: getting all  centers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Center'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Get all centers
      tags:
      - Center
  /center/delete:
    delete:
      consumes:
      - application/json
      description: delete center
      parameters:
      - description: deletecenter
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.DeleteCenter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DeleteProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Delete center
      tags:
      - Center
  /center/name/{id}:
    get:
      consumes:
      - application/json
      description: getting center name by id
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DeleteProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Get center name
      tags:
      - Center
  /center/update:
    patch:
      consumes:
      - application/json
      description: update center
      parameters:
      - description: updatecenter
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateCenter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DeleteProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Update center
      tags:
      - Center
  /protocols/{filter}/{center}:
    get:
      consumes:
      - application/json
      description: Getting all protocols from users center id and filter params
      parameters:
      - description: Filter
        in: path
        name: filter
        required: true
        type: string
      - description: Center
        in: path
        name: center
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.GetProtocols'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Protocols Get
      tags:
      - Protocol
  /protocols/add:
    post:
      consumes:
      - application/json
      description: creating a new protocol
      parameters:
      - description: addprotocol
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.AddProtocol'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.AddProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Protocol Add
      tags:
      - Protocol
  /protocols/delete:
    delete:
      consumes:
      - application/json
      description: Deleting a  protocol  by id
      parameters:
      - description: deleteprotocol
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.DeleteProtocol'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DeleteProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Protocol Delete
      tags:
      - Protocol
  /protocols/save:
    patch:
      consumes:
      - application/json
      description: saving of updating prtocol
      parameters:
      - description: saveprotocol
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.SaveProtocol'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SaveProtocol'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Protocol Save
      tags:
      - Protocol
  /user/all:
    get:
      consumes:
      - application/json
      description: getting all  of users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Registration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Get Users
      tags:
      - User
  /user/delete:
    delete:
      consumes:
      - application/json
      description: delete of user
      parameters:
      - description: delete
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.Delete'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Registration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: User Delete
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: authentification user in the system
      parameters:
      - description: login
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Login'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: User Login
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: registration of user
      parameters:
      - description: registration
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.Registration'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Registration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: User Registration
      tags:
      - User
  /user/update:
    patch:
      consumes:
      - application/json
      description: update of user
      parameters:
      - description: update
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/requests.Update'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Registration'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: User Update
      tags:
      - User
swagger: "2.0"
